### PR TITLE
[WDP-2109-01-7] Task Done

### PR DESCRIPTION
**Pull request by kai-mareving**

### CODE REVIEW

**Comment by kai-mareving** [comment]
Everything is working now. 
- Categories from initialState are maped in ProductSearch to be displayed in list that appears on :hover. 
- The list has color $primary (orange) on :hover and no longer changes the position of .root div when it appears. 
- I removed the remaining outline and fixed font-size as specified in task. 

I think this can be safely merged. Also:
- fixes missing closing } in ProductBox.module.scss.

**Review by odevpl — CHANGES_REQUESTED** [review]
Hej! Dodał bym jeszcze białe tło dla ul, bo mamy takie coś:
Zrzut ekranu 2021-09-12 o 08 55 16

**Comment by kai-mareving** [comment]
@odevpl Tło listy poprawione zgodnie z requestem.

**Review by kai-mareving — COMMENTED** [review]
Poprawione

**Pull request merged**
